# Generated by Django 4.0.1 on 2022-03-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='upcoming_meeting',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='meetings',
        ),
        migrations.AddField(
            model_name='club',
            name='club_meetings',
            field=models.ManyToManyField(related_name='club_meetings', to='api.Meeting'),
        ),
    ]
