# Generated by Django 4.0.1 on 2022-03-12 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='themes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
