# Generated by Django 4.0.1 on 2022-04-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gravatar_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
