# Generated by Django 4.0.1 on 2022-03-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default='23.03.2022 20:28:57'),
        ),
    ]
