# Generated by Django 4.0.1 on 2022-03-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover_link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
