# Generated by Django 4.0.1 on 2022-04-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ml_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.TextField(),
        ),
    ]
