# Generated by Django 4.0.1 on 2022-04-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cover_link',
        ),
    ]
