# Generated by Django 4.0.1 on 2022-03-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='notifications',
            field=models.BooleanField(default=False),
        ),
    ]
