# Generated by Django 4.0.1 on 2022-03-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='themes',
        ),
        migrations.AddField(
            model_name='club',
            name='theme',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
