# Generated by Django 4.0.1 on 2022-03-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_club_upcoming_meeting_remove_movie_meetings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
