# Generated by Django 4.0.1 on 2022-03-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_membership_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cover_link',
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='mission_statement',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='club',
            name='theme',
            field=models.CharField(max_length=20),
        ),
    ]
