# Generated by Django 4.0.1 on 2022-03-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_club_themes_club_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('M', 'Member'), ('C', 'Owner'), ('O', 'Organiser'), ('B', 'BannedMember')], default='M', max_length=1),
        ),
    ]
