# Generated by Django 4.0.1 on 2022-03-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferences',
        ),
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.ManyToManyField(related_name='preferences', to='api.Genre'),
        ),
    ]
