# Generated by Django 4.0.1 on 2022-02-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_club_user_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100, unique=True)),
                ('release_date', models.DateField()),
                ('genres', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=50)),
                ('cast', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['movie_name'],
            },
        ),
    ]
