# Generated by Django 4.0.1 on 2022-04-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_gravatar_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gravatar_link',
        ),
    ]
