# Generated by Django 4.0.1 on 2022-03-17 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='meetings',
        ),
        migrations.AddField(
            model_name='club',
            name='club_meetings',
            field=models.ManyToManyField(related_name='club_meetings', to='api.Meeting'),
        ),
        migrations.AddField(
            model_name='club',
            name='club_messages',
            field=models.ManyToManyField(related_name='club_messages', to='api.Message'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(related_name='attendees', to=settings.AUTH_USER_MODEL),
        ),
    ]
