# Generated by Django 4.0.1 on 2022-03-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_options_club_club_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='theme',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
