# Generated by Django 4.0.1 on 2022-03-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_meeting_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
