# Generated by Django 4.0.1 on 2022-03-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_movie_cover_link_movie_imdb_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='ml_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
