# Generated by Django 4.0.1 on 2022-03-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_meeting_date_alter_meeting_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_link',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
