# Generated by Django 4.0.1 on 2022-04-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_gravatar_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watch',
            options={'ordering': ('time_watched',)},
        ),
    ]
