# Generated by Django 4.0.1 on 2022-03-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_club_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='theme',
            new_name='themes',
        ),
    ]
