# Generated by Django 4.0.1 on 2022-03-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_movie_ml_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ml_id',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
