# Generated by Django 4.0.1 on 2022-03-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_meeting_meeting_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['user']},
        ),
    ]
