# Generated by Django 4.0.1 on 2022-03-23 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_username'),
        ('api', '0007_alter_meeting_completed'),
    ]

    operations = [
    ]
