# Generated by Django 4.0.1 on 2022-03-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20220323_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_organiser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('M', 'Member'), ('C', 'Owner'), ('B', 'BannedMember')], default='M', max_length=1),
        ),
    ]
