export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';

export const LOAD_USER_ACCOUNT_SUCCESS = 'LOAD_USER_ACCOUNT_SUCCESS';
export const LOAD_USER_ACCOUNT_FAIL = 'LOAD_USER_ACCOUNT_FAIL';
